// Code generated by protoc-gen-go. DO NOT EDIT.
// source: models.proto

package authpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Stored struct {
	Email                string   `protobuf:"bytes,1,opt,name=Email,json=email,proto3" json:"Email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,json=password,proto3" json:"Password,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=Token,json=token,proto3" json:"Token,omitempty"`
	Verified             bool     `protobuf:"varint,4,opt,name=Verified,json=verified,proto3" json:"Verified,omitempty"`
	AccType              int32    `protobuf:"varint,5,opt,name=AccType,json=accType,proto3" json:"AccType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Stored) Reset()         { *m = Stored{} }
func (m *Stored) String() string { return proto.CompactTextString(m) }
func (*Stored) ProtoMessage()    {}
func (*Stored) Descriptor() ([]byte, []int) {
	return fileDescriptor_models_386c2707cfb7b5c7, []int{0}
}
func (m *Stored) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Stored.Unmarshal(m, b)
}
func (m *Stored) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Stored.Marshal(b, m, deterministic)
}
func (dst *Stored) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stored.Merge(dst, src)
}
func (m *Stored) XXX_Size() int {
	return xxx_messageInfo_Stored.Size(m)
}
func (m *Stored) XXX_DiscardUnknown() {
	xxx_messageInfo_Stored.DiscardUnknown(m)
}

var xxx_messageInfo_Stored proto.InternalMessageInfo

func (m *Stored) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Stored) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Stored) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Stored) GetVerified() bool {
	if m != nil {
		return m.Verified
	}
	return false
}

func (m *Stored) GetAccType() int32 {
	if m != nil {
		return m.AccType
	}
	return 0
}

func init() {
	proto.RegisterType((*Stored)(nil), "auth.models.Stored")
}

func init() { proto.RegisterFile("models.proto", fileDescriptor_models_386c2707cfb7b5c7) }

var fileDescriptor_models_386c2707cfb7b5c7 = []byte{
	// 165 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0xc9, 0xcd, 0x4f, 0x49,
	0xcd, 0x29, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4e, 0x2c, 0x2d, 0xc9, 0xd0, 0x83,
	0x08, 0x29, 0xb5, 0x31, 0x72, 0xb1, 0x05, 0x97, 0xe4, 0x17, 0xa5, 0xa6, 0x08, 0x89, 0x70, 0xb1,
	0xba, 0xe6, 0x26, 0x66, 0xe6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0xb1, 0xa6, 0x82, 0x38,
	0x42, 0x52, 0x5c, 0x1c, 0x01, 0x89, 0xc5, 0xc5, 0xe5, 0xf9, 0x45, 0x29, 0x12, 0x4c, 0x60, 0x09,
	0x8e, 0x02, 0x28, 0x1f, 0xa4, 0x23, 0x24, 0x3f, 0x3b, 0x35, 0x4f, 0x82, 0x19, 0xa2, 0xa3, 0x04,
	0xc4, 0x01, 0xe9, 0x08, 0x4b, 0x2d, 0xca, 0x4c, 0xcb, 0x4c, 0x4d, 0x91, 0x60, 0x01, 0x4a, 0x70,
	0x04, 0x71, 0x94, 0x41, 0xf9, 0x42, 0x12, 0x5c, 0xec, 0x8e, 0xc9, 0xc9, 0x21, 0x95, 0x05, 0xa9,
	0x12, 0xac, 0x40, 0x29, 0xd6, 0x20, 0xf6, 0x44, 0x08, 0xd7, 0x89, 0x23, 0x8a, 0x0d, 0xe4, 0xae,
	0x82, 0xa4, 0x24, 0x36, 0xb0, 0x33, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xb3, 0x77, 0x78,
	0xfc, 0xb6, 0x00, 0x00, 0x00,
}
