// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package authpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_679ed93c34bb3e19, []int{0}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type AuthenticateRequest struct {
	Email                *Stored  `protobuf:"bytes,1,opt,name=Email,json=email,proto3" json:"Email,omitempty"`
	Challenge            string   `protobuf:"bytes,2,opt,name=Challenge,json=challenge,proto3" json:"Challenge,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticateRequest) Reset()         { *m = AuthenticateRequest{} }
func (m *AuthenticateRequest) String() string { return proto.CompactTextString(m) }
func (*AuthenticateRequest) ProtoMessage()    {}
func (*AuthenticateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_679ed93c34bb3e19, []int{1}
}
func (m *AuthenticateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticateRequest.Unmarshal(m, b)
}
func (m *AuthenticateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticateRequest.Marshal(b, m, deterministic)
}
func (dst *AuthenticateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticateRequest.Merge(dst, src)
}
func (m *AuthenticateRequest) XXX_Size() int {
	return xxx_messageInfo_AuthenticateRequest.Size(m)
}
func (m *AuthenticateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticateRequest proto.InternalMessageInfo

func (m *AuthenticateRequest) GetEmail() *Stored {
	if m != nil {
		return m.Email
	}
	return nil
}

func (m *AuthenticateRequest) GetChallenge() string {
	if m != nil {
		return m.Challenge
	}
	return ""
}

type AuthenticateResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticateResponse) Reset()         { *m = AuthenticateResponse{} }
func (m *AuthenticateResponse) String() string { return proto.CompactTextString(m) }
func (*AuthenticateResponse) ProtoMessage()    {}
func (*AuthenticateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_679ed93c34bb3e19, []int{2}
}
func (m *AuthenticateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticateResponse.Unmarshal(m, b)
}
func (m *AuthenticateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticateResponse.Marshal(b, m, deterministic)
}
func (dst *AuthenticateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticateResponse.Merge(dst, src)
}
func (m *AuthenticateResponse) XXX_Size() int {
	return xxx_messageInfo_AuthenticateResponse.Size(m)
}
func (m *AuthenticateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticateResponse proto.InternalMessageInfo

type RegisterRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=Email,json=email,proto3" json:"Email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,json=password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_679ed93c34bb3e19, []int{3}
}
func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (dst *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(dst, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type RegisterResponse struct {
	UID                  string   `protobuf:"bytes,1,opt,name=UID,json=uID,proto3" json:"UID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_679ed93c34bb3e19, []int{4}
}
func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (dst *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(dst, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetUID() string {
	if m != nil {
		return m.UID
	}
	return ""
}

type DeleteRequest struct {
	Email                *Stored  `protobuf:"bytes,1,opt,name=Email,json=email,proto3" json:"Email,omitempty"`
	Challenge            string   `protobuf:"bytes,2,opt,name=Challenge,json=challenge,proto3" json:"Challenge,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_679ed93c34bb3e19, []int{5}
}
func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(dst, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetEmail() *Stored {
	if m != nil {
		return m.Email
	}
	return nil
}

func (m *DeleteRequest) GetChallenge() string {
	if m != nil {
		return m.Challenge
	}
	return ""
}

type DeleteResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_679ed93c34bb3e19, []int{6}
}
func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(dst, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

type ChangePasswordRequest struct {
	Email                *Stored  `protobuf:"bytes,1,opt,name=Email,json=email,proto3" json:"Email,omitempty"`
	Challenge            string   `protobuf:"bytes,2,opt,name=Challenge,json=challenge,proto3" json:"Challenge,omitempty"`
	NewPassword          string   `protobuf:"bytes,3,opt,name=NewPassword,json=newPassword,proto3" json:"NewPassword,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangePasswordRequest) Reset()         { *m = ChangePasswordRequest{} }
func (m *ChangePasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ChangePasswordRequest) ProtoMessage()    {}
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_679ed93c34bb3e19, []int{7}
}
func (m *ChangePasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePasswordRequest.Unmarshal(m, b)
}
func (m *ChangePasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePasswordRequest.Marshal(b, m, deterministic)
}
func (dst *ChangePasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePasswordRequest.Merge(dst, src)
}
func (m *ChangePasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ChangePasswordRequest.Size(m)
}
func (m *ChangePasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePasswordRequest proto.InternalMessageInfo

func (m *ChangePasswordRequest) GetEmail() *Stored {
	if m != nil {
		return m.Email
	}
	return nil
}

func (m *ChangePasswordRequest) GetChallenge() string {
	if m != nil {
		return m.Challenge
	}
	return ""
}

func (m *ChangePasswordRequest) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

type ChangePasswordResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangePasswordResponse) Reset()         { *m = ChangePasswordResponse{} }
func (m *ChangePasswordResponse) String() string { return proto.CompactTextString(m) }
func (*ChangePasswordResponse) ProtoMessage()    {}
func (*ChangePasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_679ed93c34bb3e19, []int{8}
}
func (m *ChangePasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePasswordResponse.Unmarshal(m, b)
}
func (m *ChangePasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePasswordResponse.Marshal(b, m, deterministic)
}
func (dst *ChangePasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePasswordResponse.Merge(dst, src)
}
func (m *ChangePasswordResponse) XXX_Size() int {
	return xxx_messageInfo_ChangePasswordResponse.Size(m)
}
func (m *ChangePasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePasswordResponse proto.InternalMessageInfo

type LookupRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=Email,json=email,proto3" json:"Email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LookupRequest) Reset()         { *m = LookupRequest{} }
func (m *LookupRequest) String() string { return proto.CompactTextString(m) }
func (*LookupRequest) ProtoMessage()    {}
func (*LookupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_679ed93c34bb3e19, []int{9}
}
func (m *LookupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LookupRequest.Unmarshal(m, b)
}
func (m *LookupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LookupRequest.Marshal(b, m, deterministic)
}
func (dst *LookupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LookupRequest.Merge(dst, src)
}
func (m *LookupRequest) XXX_Size() int {
	return xxx_messageInfo_LookupRequest.Size(m)
}
func (m *LookupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LookupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LookupRequest proto.InternalMessageInfo

func (m *LookupRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type LookupResponse struct {
	Email                *Stored  `protobuf:"bytes,1,opt,name=Email,json=email,proto3" json:"Email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LookupResponse) Reset()         { *m = LookupResponse{} }
func (m *LookupResponse) String() string { return proto.CompactTextString(m) }
func (*LookupResponse) ProtoMessage()    {}
func (*LookupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_679ed93c34bb3e19, []int{10}
}
func (m *LookupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LookupResponse.Unmarshal(m, b)
}
func (m *LookupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LookupResponse.Marshal(b, m, deterministic)
}
func (dst *LookupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LookupResponse.Merge(dst, src)
}
func (m *LookupResponse) XXX_Size() int {
	return xxx_messageInfo_LookupResponse.Size(m)
}
func (m *LookupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LookupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LookupResponse proto.InternalMessageInfo

func (m *LookupResponse) GetEmail() *Stored {
	if m != nil {
		return m.Email
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "auth.service.Empty")
	proto.RegisterType((*AuthenticateRequest)(nil), "auth.service.AuthenticateRequest")
	proto.RegisterType((*AuthenticateResponse)(nil), "auth.service.AuthenticateResponse")
	proto.RegisterType((*RegisterRequest)(nil), "auth.service.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "auth.service.RegisterResponse")
	proto.RegisterType((*DeleteRequest)(nil), "auth.service.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "auth.service.DeleteResponse")
	proto.RegisterType((*ChangePasswordRequest)(nil), "auth.service.ChangePasswordRequest")
	proto.RegisterType((*ChangePasswordResponse)(nil), "auth.service.ChangePasswordResponse")
	proto.RegisterType((*LookupRequest)(nil), "auth.service.LookupRequest")
	proto.RegisterType((*LookupResponse)(nil), "auth.service.LookupResponse")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_service_679ed93c34bb3e19) }

var fileDescriptor_service_679ed93c34bb3e19 = []byte{
	// 394 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xb4, 0x93, 0x4f, 0x4f, 0xe2, 0x40,
	0x18, 0xc6, 0xc3, 0x76, 0x61, 0xdb, 0x97, 0x3f, 0x4b, 0x06, 0x96, 0x90, 0x2e, 0xbb, 0x61, 0x67,
	0xd9, 0x64, 0xbd, 0xf4, 0x80, 0x47, 0x4f, 0x0a, 0x1e, 0x48, 0x8c, 0x31, 0x35, 0x24, 0x46, 0x13,
	0x93, 0x02, 0x6f, 0xa0, 0xb1, 0x74, 0x6a, 0x67, 0x2a, 0xf1, 0xea, 0x17, 0xf0, 0x2b, 0xdb, 0xd2,
	0xa9, 0x30, 0x0d, 0x12, 0x0f, 0x7a, 0x64, 0x9e, 0x87, 0xdf, 0x3c, 0xf3, 0x3e, 0x6f, 0xa1, 0xca,
	0x31, 0x7c, 0x70, 0xa7, 0x68, 0x05, 0x21, 0x13, 0x8c, 0x54, 0x9c, 0x48, 0x2c, 0x2c, 0x79, 0x66,
	0x56, 0x96, 0x6c, 0x86, 0x1e, 0x4f, 0x35, 0xfa, 0x0d, 0x8a, 0xa7, 0xcb, 0x40, 0x3c, 0xd2, 0x5b,
	0x68, 0x1c, 0xc7, 0x36, 0xf4, 0x85, 0x3b, 0x75, 0x04, 0xda, 0x78, 0x1f, 0x21, 0x17, 0xe4, 0x20,
	0xd1, 0x1d, 0xd7, 0x6b, 0x17, 0xba, 0x85, 0xff, 0xe5, 0x7e, 0xc3, 0x5a, 0xb3, 0x24, 0xe2, 0x52,
	0xb0, 0x10, 0x67, 0x76, 0x11, 0x13, 0x07, 0xe9, 0x80, 0x31, 0x58, 0x38, 0x9e, 0x87, 0xfe, 0x1c,
	0xdb, 0x5f, 0x62, 0xbb, 0x61, 0x1b, 0xd3, 0xec, 0x80, 0xb6, 0xa0, 0xa9, 0xf2, 0x79, 0xc0, 0x7c,
	0x8e, 0x74, 0x00, 0xdf, 0x6d, 0x9c, 0xbb, 0x5c, 0x60, 0x98, 0xdd, 0xd9, 0xdc, 0xbe, 0xd3, 0xc8,
	0xf0, 0x26, 0xe8, 0x17, 0x0e, 0xe7, 0x2b, 0x16, 0xce, 0x24, 0x5d, 0x0f, 0xe4, 0x6f, 0xda, 0x83,
	0xfa, 0x06, 0x92, 0x82, 0x49, 0x1d, 0xb4, 0xf1, 0x68, 0x28, 0x19, 0x5a, 0x34, 0x1a, 0xd2, 0x2b,
	0xa8, 0x0e, 0xd1, 0xc3, 0x4f, 0x78, 0x5c, 0x1d, 0x6a, 0x19, 0x59, 0x3e, 0xeb, 0xa9, 0x00, 0x3f,
	0xe2, 0x3f, 0xc4, 0x62, 0x16, 0xfa, 0xa3, 0x2f, 0x25, 0x5d, 0x28, 0x9f, 0xe3, 0xea, 0x75, 0x26,
	0xda, 0x5a, 0x2f, 0xfb, 0x9b, 0x23, 0xda, 0x86, 0x56, 0x3e, 0x83, 0x8c, 0xf7, 0x0f, 0xaa, 0x67,
	0x8c, 0xdd, 0x45, 0xc1, 0xde, 0x99, 0xd3, 0x23, 0xa8, 0x65, 0x36, 0x39, 0xd5, 0xf7, 0xa7, 0xef,
	0x3f, 0x6b, 0xf0, 0x35, 0xa9, 0x9c, 0x8c, 0xa1, 0xb2, 0x5d, 0x3d, 0xf9, 0x63, 0x6d, 0x2f, 0xa4,
	0xb5, 0x63, 0xed, 0x4c, 0xba, 0xcf, 0x22, 0xa3, 0x8c, 0x40, 0xcf, 0x4a, 0x27, 0xbf, 0x54, 0x7f,
	0x6e, 0xa3, 0xcc, 0xdf, 0x6f, 0xc9, 0x12, 0x35, 0x80, 0x52, 0xda, 0x1f, 0xf9, 0xa9, 0x3a, 0x95,
	0x7d, 0x31, 0x3b, 0xbb, 0x45, 0x09, 0xb9, 0x81, 0x9a, 0x3a, 0x6d, 0xf2, 0x57, 0xf5, 0xef, 0xdc,
	0x07, 0xb3, 0xb7, 0xdf, 0xb4, 0x49, 0x98, 0x36, 0x91, 0x4f, 0xa8, 0xd4, 0x98, 0x4f, 0xa8, 0x96,
	0x77, 0xa2, 0x5f, 0x97, 0x12, 0x39, 0x98, 0x4c, 0x4a, 0xeb, 0xaf, 0xff, 0xf0, 0x25, 0x00, 0x00,
	0xff, 0xff, 0xe0, 0xe8, 0x1f, 0xb8, 0x2a, 0x04, 0x00, 0x00,
}
